/**
 * PROJECT: GEEK INFOTECH AMS V1.2.0
 * SCOPE: Core Authority, Academic, Identity & Audit
 */

CREATE TABLE GIAMS_MST_STAFF (
    STAFF_ID INT AUTO_INCREMENT PRIMARY KEY,
    STAFF_CODE VARCHAR(20) UNIQUE NOT NULL,
    FULL_NAME VARCHAR(100) NOT NULL,
    DESIGNATION VARCHAR(50),
    MOBILE_NO VARCHAR(255),
    EMAIL_ID VARCHAR(150),
    IS_ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE GIAMS_AUDIT_LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    USER_ID INT NULL,
    USERNAME VARCHAR(50) NULL,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    USER_AGENT TEXT,
    REQUEST_URL TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE GIAMS_MST_COURSES (
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_CODE VARCHAR(20) UNIQUE NOT NULL,
    COURSE_NAME VARCHAR(100) NOT NULL,
    DURATION_MONTHS INT NOT NULL,
    TOTAL_FEES DECIMAL(10,2) NOT NULL,
    IS_ACTIVE TINYINT(1) DEFAULT 1,
    MAKER_ID INT NOT NULL,
    MAKER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTH_ID INT NULL,
    AUTH_DATE DATETIME NULL,
    CONSTRAINT FK_COURSE_MAKER FOREIGN KEY (MAKER_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT FK_COURSE_AUTH FOREIGN KEY (AUTH_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID)
) ENGINE=INNODB;

CREATE TABLE GIAMS_MST_STUDENTS (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMISSION_NO VARCHAR(20) UNIQUE NOT NULL,
    FULL_NAME VARCHAR(100) NOT NULL,
    FATHER_NAME VARCHAR(100),
    MOTHER_NAME VARCHAR(100),
    MOBILE_NO VARCHAR(255) NOT NULL,
    EMAIL_ID VARCHAR(150),
    AADHAAR_NO VARCHAR(255),
    COURSE_ID INT,
    ADMISSION_DATE DATE NOT NULL,
    IS_ACTIVE TINYINT(1) DEFAULT 0,
    MAKER_ID INT NOT NULL,
    MAKER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTH_ID INT NULL,
    AUTH_DATE DATETIME NULL,
    CONSTRAINT FK_STUDENT_COURSE FOREIGN KEY (COURSE_ID) REFERENCES GIAMS_MST_COURSES(COURSE_ID),
    CONSTRAINT FK_STUDENT_MAKER FOREIGN KEY (MAKER_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT FK_STUDENT_AUTH FOREIGN KEY (AUTH_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT CHK_STUDENT_MAKER_CHECKER CHECK (MAKER_ID <> AUTH_ID)
) ENGINE=INNODB;

CREATE TABLE GIAMS_MST_USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    STAFF_REF_ID INT NULL,
    STUDENT_REF_ID INT NULL,
    ROLE ENUM('ADMIN', 'COUNSELOR', 'FACULTY', 'STUDENT') NOT NULL,
    IS_ACTIVE TINYINT(1) DEFAULT 0,
    MAKER_ID INT NOT NULL,
    MAKER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTH_ID INT NULL,
    AUTH_DATE DATETIME NULL,
    LAST_LOGIN_AT DATETIME NULL,
    LAST_LOGIN_IP VARCHAR(45) NULL,
    CONSTRAINT FK_USER_STAFF_REF FOREIGN KEY (STAFF_REF_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT FK_USER_STUDENT_REF FOREIGN KEY (STUDENT_REF_ID) REFERENCES GIAMS_MST_STUDENTS(STUDENT_ID),
    CONSTRAINT FK_USER_MAKER FOREIGN KEY (MAKER_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT FK_USER_AUTH FOREIGN KEY (AUTH_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT CHK_MAKER_CHECKER_DIFF CHECK (MAKER_ID <> AUTH_ID)
) ENGINE=INNODB;

CREATE TABLE GIAMS_FEE_MASTER (
    FEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    TOTAL_PAYABLE DECIMAL(10,2) NOT NULL,
    DISCOUNT_ALLOWED DECIMAL(10,2) DEFAULT 0.00,
    NET_PAYABLE DECIMAL(10,2) AS (TOTAL_PAYABLE - DISCOUNT_ALLOWED) STORED,
    PAID_AMOUNT DECIMAL(10,2) DEFAULT 0.00,
    BALANCE_AMOUNT DECIMAL(10,2) AS (TOTAL_PAYABLE - DISCOUNT_ALLOWED - PAID_AMOUNT) STORED,
    MAKER_ID INT NOT NULL,
    MAKER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTH_ID INT NULL,
    AUTH_DATE DATETIME NULL,
    CONSTRAINT FK_FEE_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES GIAMS_MST_STUDENTS(STUDENT_ID),
    CONSTRAINT FK_FEE_COURSE FOREIGN KEY (COURSE_ID) REFERENCES GIAMS_MST_COURSES(COURSE_ID),
    CONSTRAINT FK_FEE_MAKER FOREIGN KEY (MAKER_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT FK_FEE_AUTH FOREIGN KEY (AUTH_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID)
) ENGINE=INNODB;

CREATE TABLE GIAMS_FEE_LEDGER (
    TRX_ID INT AUTO_INCREMENT PRIMARY KEY,
    FEE_ID INT NOT NULL,
    RECEIPT_NO VARCHAR(50) UNIQUE NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    AMOUNT_PAID DECIMAL(10,2) NOT NULL,
    PAYMENT_MODE ENUM('CASH', 'UPI', 'BANK_TRANSFER', 'CHEQUE') NOT NULL,
    REMARKS TEXT,
    MAKER_ID INT NOT NULL,
    MAKER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTH_ID INT NULL,
    AUTH_DATE DATETIME NULL,
    CONSTRAINT FK_LEDGER_MASTER FOREIGN KEY (FEE_ID) REFERENCES GIAMS_FEE_MASTER(FEE_ID),
    CONSTRAINT FK_LEDGER_MAKER FOREIGN KEY (MAKER_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT FK_LEDGER_AUTH FOREIGN KEY (AUTH_ID) REFERENCES GIAMS_MST_STAFF(STAFF_ID),
    CONSTRAINT CHK_FINANCE_MAKER_CHECKER CHECK (MAKER_ID <> AUTH_ID)
) ENGINE=INNODB;
